apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-redlock-laboratory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-app
  template:
    metadata:
      labels:
        app: web-server-app
    spec:
      containers:
        - name: redlock-web-server
          imagePullPolicy: Never
          image: redlock-web-server
          ports:
            - containerPort: 80
          env:
            - name: NODE_PORT
              value: "80"
          