version: "3.2"

services:
  web-server:
    container_name: web-server
    image: redlock-web-server
    build:
      context: ./web-server/
    environment:
      NODE_PORT: 80

  cron-service:
    container_name: cron-service
    image: redlock-cron-service
    build:
      context: ./cron-service/
    depends_on:
      - web-server
      - redis
    environment:
      WEB_SERVER_HOST: "web-server"
      REDIS_HOST: "redis"

  redis:
    container_name: redis
    image: redis

